// Hand-built sample lexicons. Swap these arrays for frequency-ranked corpus
// lists (e.g. OpenSubtitles) to scale up; nothing else needs to change.
/* [word, gloss, loan?] — loan flags shared internationalisms */
const PL = [
["sól","salt"],["mól","moth"],["ból","pain"],["stół","table"],["dół","pit"],["wół","ox"],
["sam","alone, self"],["tam","there"],["pan","mister, sir"],["pani","madam"],["tak","yes"],
["nie","no"],["kot","cat"],["pies","dog"],["dom","house"],["noc","night"],["dzień","day"],
["rok","year"],["czas","time"],["woda","water"],["ogień","fire"],["ziemia","earth"],
["niebo","sky"],["słońce","sun"],["księżyc","moon"],["gwiazda","star"],["chleb","bread"],
["mleko","milk"],["ser","cheese"],["mięso","meat"],["ryba","fish"],["jajko","egg"],
["sok","juice"],["herbata","tea"],["kawa","coffee"],["piwo","beer"],["wino","wine"],
["cukier","sugar"],["masło","butter"],["zupa","soup"],["obiad","lunch"],["nos","nose"],
["oko","eye"],["ucho","ear"],["usta","mouth"],["ręka","hand, arm"],["noga","leg"],
["głowa","head"],["serce","heart"],["krew","blood"],["kość","bone"],["skóra","skin"],
["włosy","hair"],["ząb","tooth"],["palec","finger"],["twarz","face"],["plecy","back"],
["matka","mother"],["ojciec","father"],["syn","son"],["córka","daughter"],["brat","brother"],
["siostra","sister"],["żona","wife"],["mąż","husband"],["dziecko","child"],["rodzina","family"],
["przyjaciel","friend"],["człowiek","person"],["kobieta","woman"],["mężczyzna","man"],
["chłopiec","boy"],["dziewczyna","girl"],["miasto","city"],["wieś","village"],["kraj","country"],
["droga","road"],["ulica","street"],["most","bridge"],["rzeka","river"],["morze","sea"],
["góra","mountain"],["las","forest"],["pole","field"],["ogród","garden"],["drzewo","tree"],
["kwiat","flower"],["trawa","grass"],["liść","leaf"],["owoc","fruit"],["jabłko","apple"],
["dziś","today"],["jutro","tomorrow"],["wczoraj","yesterday"],["teraz","now"],["potem","later"],
["zawsze","always"],["nigdy","never"],["często","often"],["rano","morning"],["wieczór","evening"],
["tydzień","week"],["miesiąc","month"],["wiosna","spring"],["lato","summer"],["jesień","autumn"],
["zima","winter"],["dobry","good"],["zły","bad"],["duży","big"],["mały","small"],
["nowy","new"],["stary","old"],["długi","long"],["krótki","short"],["wysoki","tall"],
["niski","low"],["ciepły","warm"],["zimny","cold"],["gorący","hot"],["mokry","wet"],
["suchy","dry"],["pełny","full"],["pusty","empty"],["ciężki","heavy"],["lekki","light"],
["szybki","fast"],["wolny","slow, free"],["ładny","pretty"],["brzydki","ugly"],["młody","young"],
["biały","white"],["czarny","black"],["czerwony","red"],["zielony","green"],["niebieski","blue"],
["żółty","yellow"],["szary","grey"],["jeden","one"],["dwa","two"],["trzy","three"],
["cztery","four"],["pięć","five"],["sześć","six"],["siedem","seven"],["osiem","eight"],
["dziewięć","nine"],["dziesięć","ten"],["sto","hundred"],["tysiąc","thousand"],["pół","half"],
["być","to be"],["mieć","to have"],["robić","to do"],["iść","to go"],["jeść","to eat"],
["pić","to drink"],["spać","to sleep"],["mówić","to speak"],["widzieć","to see"],["słyszeć","to hear"],
["wiedzieć","to know"],["chcieć","to want"],["móc","to be able"],["dać","to give"],["brać","to take"],
["pisać","to write"],["czytać","to read"],["kupić","to buy"],["myśleć","to think"],["kochać","to love"],
["ja","I"],["ty","you"],["on","he"],["ona","she"],["my","we"],["wy","you (pl)"],["oni","they"],
["mnie","me"],["ciebie","you (acc)"],["nam","to us"],["wam","to you (pl)"],["nim","him (instr)"],
["ten","this"],["ta","this (f)"],["to","this, it"],["tu","here"],["tutaj","right here"],
["gdzie","where"],["kiedy","when"],["jak","how"],["co","what"],["kto","who"],["kim","whom (instr)"],
["dlaczego","why"],["ile","how much"],["i","and"],["ale","but"],["albo","or"],["bo","because"],
["ani","nor, not even"],["już","already"],["jeszcze","still, yet"],["bardzo","very"],["tylko","only"],
["może","maybe"],["nawet","even"],["znowu","again"],["razem","together"],["osobno","separately"],
["praca","work"],["szkoła","school"],["książka","book"],["gazeta","newspaper"],["list","letter"],
["słowo","word"],["język","language, tongue"],["głos","voice"],["muzyka","music"],["piosenka","song"],
["obraz","picture"],["film","film",true],["gra","game"],["zabawa","fun"],["sport","sport",true],
["piłka","ball"],["gol","goal",true],["taniec","dance"],["teatr","theatre",true],["kino","cinema",true],
["pieniądze","money"],["cena","price"],["sklep","shop"],["rynek","market"],["kasa","cash desk"],
["bank","bank",true],["konto","account"],["klucz","key"],["drzwi","door"],["okno","window"],
["ściana","wall"],["dach","roof"],["podłoga","floor"],["pokój","room, peace"],["kuchnia","kitchen"],
["łóżko","bed"],["stolik","small table"],["krzesło","chair"],["szafa","wardrobe"],["lampa","lamp",true],
["auto","car",true],["pociąg","train"],["samolot","airplane"],["statek","ship"],["rower","bicycle"],
["bilet","ticket",true],["podróż","journey"],["hotel","hotel",true],["plaża","beach"],["góry","mountains"],
["ptak","bird"],["koń","horse"],["krowa","cow"],["świnia","pig"],["owca","sheep"],
["kura","hen"],["mysz","mouse"],["wilk","wolf"],["niedźwiedź","bear"],["lis","fox"],
["mucha","fly"],["pszczoła","bee"],["motyl","butterfly"],["wąż","snake"],["żaba","frog"],
["deszcz","rain"],["śnieg","snow"],["wiatr","wind"],["burza","storm"],["chmura","cloud"],
["mgła","fog"],["lód","ice"],["ciepło","warmth"],["mróz","frost"],["cień","shadow"],
["kolor","colour",true],["kształt","shape"],["linia","line",true],["punkt","point",true],["koło","circle, wheel"],
["numer","number",true],["strona","page, side"],["środek","middle"],["koniec","end"],["początek","beginning"],
["prawda","truth"],["kłamstwo","lie"],["sen","dream, sleep"],["myśl","thought"],["uczucie","feeling"],
["radość","joy"],["smutek","sadness"],["strach","fear"],["złość","anger"],["nadzieja","hope"],
["siła","strength"],["moc","power"],["władza","authority"],["wojna","war"],["zgoda","accord"],
["prawo","law, right"],["sąd","court"],["więzienie","prison"],["policja","police",true],["wojsko","army"],
["lekarz","doctor"],["szpital","hospital",true],["choroba","illness"],["lek","medicine"],["zdrowie","health"],
["migrena","migraine",true],["rana","wound"],["śmierć","death"],["życie","life"],["ciało","body"],
["dusza","soul"],["bóg","god"],["kościół","church"],["modlitwa","prayer"],["święto","holiday"],
["warsztat","workshop"],["narzędzie","tool"],["nóż","knife"],["widelec","fork"],["łyżka","spoon"],
["talerz","plate"],["szklanka","glass"],["butelka","bottle"],["garnek","pot"],["patelnia","pan"],
["solniczka","salt shaker"],["pieprz","pepper"],["mąka","flour"],["ryż","rice"],["makaron","pasta"],
["ziemniak","potato"],["marchew","carrot"],["cebula","onion"],["czosnek","garlic"],["pomidor","tomato"],
["kapusta","cabbage"],["grzyb","mushroom"],["orzech","nut"],["miód","honey"],["olej","oil"],
["ogon","tail"],["skrzydło","wing"],["pióro","feather, pen"],["róg","horn, corner"],["łapa","paw"],
["kamień","stone"],["piasek","sand"],["glina","clay"],["żelazo","iron"],["złoto","gold"],
["srebro","silver"],["miedź","copper"],["szkło","glass (material)"],["papier","paper",true],["drewno","wood"],
["nić","thread"],["igła","needle"],["sukienka","dress"],["spodnie","trousers"],["koszula","shirt"],
["buty","shoes"],["czapka","cap"],["płaszcz","coat"],["szalik","scarf"],["rękawiczki","gloves"],
["torba","bag"],["walizka","suitcase"],["portfel","wallet"],["zegar","clock"],["telefon","telephone",true],
["radio","radio",true],["komputer","computer",true],["internet","internet",true],["poczta","post"],["wiadomość","message"],
["nazwa","name (of thing)"],["imię","first name"],["adres","address",true],["mapa","map",true],["plan","plan",true],
["ryzyko","risk",true],["szansa","chance",true],["problem","problem",true],["pytanie","question"],["odpowiedź","answer"],
["ciasto","cake, dough"],["cisza","silence"],["kasza","groats"],["kara","punishment"],["para","pair, steam"],
["mama","mum"],["tata","dad"],["baba","old woman"],["dziadek","grandfather"],["babcia","grandmother"],
["wnuk","grandson"],["ciotka","aunt"],["wujek","uncle"],["kuzyn","cousin"],["sąsiad","neighbour"],
["nara","see ya (slang)"],["cześć","hi"],["dzięki","thanks"],["proszę","please"],["przepraszam","sorry"],
["dobranoc","goodnight"],["wesoły","cheerful"],["smutny","sad"],["mądry","wise"],["głupi","stupid"],
["silny","strong"],["słaby","weak"],["bogaty","rich"],["biedny","poor"],["czysty","clean"],
["brudny","dirty"],["ostry","sharp"],["tępy","blunt"],["gruby","thick, fat"],["cienki","thin"],
["prosty","straight, simple"],["krzywy","crooked"],["okrągły","round"],["kwadrat","square"],["miękki","soft"],
["twardy","hard"],["gładki","smooth"],["szorstki","rough"],["jasny","bright"],["ciemny","dark"],
["głośny","loud"],["cichy","quiet"],["słodki","sweet"],["gorzki","bitter"],["kwaśny","sour"],
["słony","salty"],["świeży","fresh"],["stęchły","stale"],["dojrzały","ripe"],["surowy","raw"],
["wtorek","Tuesday"],["środa","Wednesday"],["piątek","Friday"],["sobota","Saturday"],["niedziela","Sunday"],
["styczeń","January"],["maj","May"],["lipiec","July"],["sierpień","August"],["grudzień","December"],
["mur","wall (brick)"],["wieża","tower"],["zamek","castle, lock"],["pałac","palace"],["ruina","ruin",true],
["ognisko","bonfire"],["dym","smoke"],["popiół","ash"],["węgiel","coal"],["iskra","spark"],
["fala","wave"],["prąd","current"],["światło","light"],["dźwięk","sound"],["zapach","smell"],
["smak","taste"],["dotyk","touch"],["wzrok","sight"],["słuch","hearing"],["pamięć","memory"],
["rozum","reason"],["wola","will"],["sumienie","conscience"],["wiara","faith"],["miłość","love"],
];

const KO = [
["물","water"],["술","liquor"],["삼","three; ginseng"],["담","wall, fence"],["남","south; stranger"],
["반","half; class"],["닭","chicken"],["속","inside"],["곳","place"],["옷","clothes"],
["김","seaweed; Kim"],["가사","lyrics"],["나라","country"],["아니","no, not"],["바보","fool"],
["한국","Korea"],["사람","person"],["시간","time, hour"],["안녕","hello"],["학교","school"],
["집","house"],["방","room"],["문","door"],["창문","window"],["벽","wall"],
["지붕","roof"],["바닥","floor"],["부엌","kitchen"],["침대","bed"],["의자","chair"],
["책상","desk"],["책","book"],["신문","newspaper"],["편지","letter"],["말","word; horse"],
["글","writing"],["소리","sound"],["목소리","voice"],["음악","music"],["노래","song"],
["그림","picture"],["영화","film"],["사진","photograph"],["춤","dance"],["연극","play, theatre"],
["돈","money"],["값","price"],["가게","shop"],["시장","market"],["은행","bank"],
["열쇠","key"],["시계","clock, watch"],["전화","telephone"],["편지지","letter paper"],["소식","news"],
["이름","name"],["주소","address"],["지도","map"],["계획","plan"],["문제","problem"],
["질문","question"],["대답","answer"],["기회","chance"],["위험","danger"],["안전","safety"],
["밥","cooked rice, meal"],["빵","bread"],["국","soup"],["고기","meat"],["생선","fish (food)"],
["계란","egg"],["우유","milk"],["치즈","cheese",true],["설탕","sugar"],["소금","salt"],
["기름","oil"],["차","tea; car"],["커피","coffee",true],["맥주","beer"],["포도주","wine"],
["주스","juice",true],["과일","fruit"],["사과","apple"],["배","pear; belly; boat"],["감","persimmon"],
["딸기","strawberry"],["수박","watermelon"],["야채","vegetable"],["감자","potato"],["당근","carrot"],
["양파","onion"],["마늘","garlic"],["배추","napa cabbage"],["버섯","mushroom"],["꿀","honey"],
["쌀","uncooked rice"],["국수","noodles"],["떡","rice cake"],["김치","kimchi"],["된장","soybean paste"],
["코","nose"],["눈","eye; snow"],["귀","ear"],["입","mouth"],["손","hand"],
["발","foot"],["다리","leg; bridge"],["팔","arm; eight"],["머리","head, hair"],["가슴","chest"],
["배꼽","navel"],["등","back"],["피","blood"],["뼈","bone"],["살","flesh"],
["얼굴","face"],["이","tooth; this"],["혀","tongue"],["목","neck, throat"],["어깨","shoulder"],
["엄마","mum"],["아빠","dad"],["어머니","mother"],["아버지","father"],["아들","son"],
["딸","daughter"],["형","older brother (of male)"],["누나","older sister (of male)"],["언니","older sister (of female)"],["동생","younger sibling"],
["아내","wife"],["남편","husband"],["아이","child"],["가족","family"],["친구","friend"],
["여자","woman"],["남자","man"],["아기","baby"],["할머니","grandmother"],["할아버지","grandfather"],
["도시","city"],["시골","countryside"],["길","road"],["시내","downtown, stream"],["강","river"],
["바다","sea"],["산","mountain"],["숲","forest"],["들","field"],["정원","garden"],
["나무","tree"],["꽃","flower"],["풀","grass"],["잎","leaf"],["뿌리","root"],
["하늘","sky"],["땅","ground"],["해","sun; year"],["달","moon; month"],["별","star"],
["불","fire"],["바람","wind"],["비","rain"],["구름","cloud"],["안개","fog"],
["얼음","ice"],["돌","stone"],["모래","sand"],["흙","soil"],["쇠","iron"],
["금","gold"],["은","silver"],["유리","glass"],["종이","paper"],["나무판","wooden board"],
["오늘","today"],["내일","tomorrow"],["어제","yesterday"],["지금","now"],["나중","later"],
["항상","always"],["절대","never, absolutely"],["자주","often"],["아침","morning"],["저녁","evening"],
["밤","night; chestnut"],["낮","daytime"],["주","week"],["년","year"],["봄","spring"],
["여름","summer"],["가을","autumn"],["겨울","winter"],["날","day"],["때","time, moment"],
["하나","one"],["둘","two"],["셋","three"],["넷","four"],["다섯","five"],
["여섯","six"],["일곱","seven"],["여덟","eight"],["아홉","nine"],["열","ten; fever"],
["백","hundred"],["천","thousand"],["만","ten thousand"],["일","one; work; day"],["이십","twenty"],
["나","I"],["너","you"],["우리","we"],["그","he, that"],["그녀","she"],
["여기","here"],["거기","there"],["저기","over there"],["어디","where"],["언제","when"],
["누구","who"],["무엇","what"],["왜","why"],["어떻게","how"],["얼마","how much"],
["그리고","and"],["그러나","but"],["또는","or"],["왜냐하면","because"],["만약","if"],
["이미","already"],["아직","still, yet"],["아주","very"],["단지","only"],["아마","maybe"],
["함께","together"],["따로","separately"],["다시","again"],["먼저","first"],["마지막","last"],
["좋다","to be good"],["나쁘다","to be bad"],["크다","to be big"],["작다","to be small"],["새","new; bird"],
["늙다","to grow old"],["길다","to be long"],["짧다","to be short"],["높다","to be high"],["낮다","to be low"],
["덥다","to be hot"],["춥다","to be cold"],["따뜻하다","to be warm"],["차갑다","to be chilly"],["젖다","to get wet"],
["마르다","to dry"],["가득","full"],["비다","to be empty"],["무겁다","to be heavy"],["가볍다","to be light"],
["빠르다","to be fast"],["느리다","to be slow"],["예쁘다","to be pretty"],["젊다","to be young"],["강하다","to be strong"],
["약하다","to be weak"],["부자","rich person"],["가난","poverty"],["깨끗","clean"],["더럽다","to be dirty"],
["하얀","white"],["검은","black"],["빨강","red"],["초록","green"],["파랑","blue"],
["노랑","yellow"],["회색","grey"],["보라","purple"],["갈색","brown"],["색","colour"],
["가다","to go"],["오다","to come"],["보다","to see"],["듣다","to hear"],["먹다","to eat"],
["마시다","to drink"],["자다","to sleep"],["말하다","to speak"],["알다","to know"],["모르다","to not know"],
["하다","to do"],["주다","to give"],["받다","to receive"],["사다","to buy"],["팔다","to sell"],
["쓰다","to write; be bitter"],["읽다","to read"],["일하다","to work"],["놀다","to play"],["웃다","to laugh"],
["울다","to cry"],["앉다","to sit"],["서다","to stand"],["걷다","to walk"],["뛰다","to run"],
["살다","to live"],["죽다","to die"],["사랑","love"],["미움","hatred"],["기쁨","joy"],
["슬픔","sadness"],["두려움","fear"],["화","anger"],["희망","hope"],["꿈","dream"],
["마음","heart, mind"],["생각","thought"],["기억","memory"],["힘","strength"],["정신","spirit"],
["몸","body"],["영혼","soul"],["신","god"],["교회","church"],["절","temple; bow"],
["기도","prayer"],["법","law"],["경찰","police"],["군대","army"],["전쟁","war"],
["평화","peace"],["병원","hospital"],["의사","doctor"],["약","medicine"],["병","illness; bottle"],
["건강","health"],["상처","wound"],["죽음","death"],["삶","life"],["일생","lifetime"],
["칼","knife"],["숟가락","spoon"],["젓가락","chopsticks"],["그릇","bowl"],["컵","cup",true],
["냄비","pot"],["가방","bag"],["지갑","wallet"],["옷장","wardrobe"],["신발","shoes"],
["모자","hat"],["바지","trousers"],["치마","skirt"],["양말","socks"],["장갑","gloves"],
["차표","ticket"],["기차","train"],["비행기","airplane"],["자전거","bicycle"],["여행","travel"],
["호텔","hotel",true],["방문","visit"],["손님","guest"],["주인","owner"],["이웃","neighbour"],
["개","dog"],["고양이","cat"],["소","cow"],["돼지","pig"],["양","sheep"],
["말고기","horse meat"],["쥐","mouse"],["늑대","wolf"],["곰","bear"],["여우","fox"],
["새우","shrimp"],["벌","bee; punishment"],["나비","butterfly"],["뱀","snake"],["개구리","frog"],
["연기","smoke"],["재","ash"],["석탄","coal"],["빛","light"],["그림자","shadow"],
["냄새","smell"],["맛","taste"],["느낌","feeling"],["소원","wish"],["진실","truth"],
["거짓","falsehood"],["비밀","secret"],["약속","promise"],["선물","gift"],["잔치","feast"],
["집안일","housework"],["일자리","job"],["회사","company"],["사무실","office"],["공장","factory"],
["끈","string, strap"],["구두","dress shoes"],["단추","button"],["실","thread"],["바늘","needle"],
["종","bell"],["북","drum; north"],["피리","flute"],["줄","line, string"],["점","dot, point"],
["원","circle; won"],["끝","end"],["처음","beginning"],["가운데","middle"],["쪽","side, direction"],
["사자","lion"],["호랑이","tiger"],["토끼","rabbit"],["거북","turtle"],["물고기","fish"],
["사탕","candy"],["과자","snack"],["국물","broth"],["반찬","side dish"],["식사","meal"],
];


export { PL, KO };
